from workers import DurableObject, Response, WorkerEntrypoint
import json
from utils import (
    gen_chat_uuid,
    gen_idea_uuid,
    get_chat_id_from_url,
    get_query_param,
    gen_user_uuid
)
from uuid import uuid4
import uuid

#____________ Message Infrastructure For AI ______________
"""
Message Infrastructure for AI (STRICT)

The model MUST output valid JSON ONLY (no backticks, no extra text).
Keys MUST be exactly: tool, args, message (all lowercase).

Schema:
{
  "tool": one of ["add_idea","delete_idea","refine_idea","update_idea","list_ideas"] or null,
  "args": object or null,
  "message": string,
}

Args by tool:
- add_idea:
  {"title": str, "description": str}

- list_ideas:
  {}  (or null)

- delete_idea:
  {"id": str}

- refine_idea:
  {"id": str, "instruction": str}   # instruction can be "" to mean "refine it"

- update_idea:
  {"id": str, "title": str|null, "description": str|null}

If tool is null:
- args must be null
- message is the assistant reply to display

Notes:
- IDs are generated by the backend.
- The model must never invent IDs; it should request list_ideas or ask a clarifying question if needed.
"""

#____________ Chat Durable Object (DO) Storage Format ____________
"""
uuid{
  "title": "Scholarship ideas",
  "messages": [
    {"role": "user", "content": "Help me refine this"},
    {"role": "assistant", "content": "Here is a refined version"}
  ]
} #stored directly in DO
"""

#_______________  IDEA Durable Object (DO) Storage Format _____________________
SYSTEM_PROMPT = """
You are a helpful assistant for an idea bank application. You help users brainstorm, refine, and manage their ideas.

You must ALWAYS return valid JSON only. No markdown, no code fences, no extra text.

Output format:
{
  "tool": "<tool name or null>",
  "args": <object or null>,
  "message": "<your conversational reply to the user>",
  "title": "<short conversation title on first message only, otherwise null>"
}

Available tools: "add_idea", "delete_idea", "refine_idea", "update_idea", "list_ideas", "get_idea"

CRITICAL BEHAVIOR RULES:

1. BE CONVERSATIONAL FIRST.
   - If the user is brainstorming or asking for suggestions, discuss ideas naturally in `message`.
   - Do NOT call a tool unless the user explicitly confirms they want to save/add/delete/update something.
   - Examples of explicit confirmation: "add that", "save it", "yes go ahead", "delete the first one".

2. ONLY call a tool when the user clearly intends an action:
   - "add_idea" → user says to save or add a specific idea
   - "list_ideas" → user asks to see their saved ideas
   - "delete_idea" → user asks to remove a specific idea (id must be known)
   - "refine_idea" → user asks to refine a saved idea (id must be known)
   - "update_idea" → user asks to change a saved idea (id must be known)
   - "get_idea" → user asks to see full details of a specific saved idea

3. When tool is null, write a full helpful reply in `message`. This is your main response.

4. When a tool IS called, `message` should confirm what was done in a friendly sentence.

5. STRICTLY NEVER ADD ID, the id will be generated by the backend

6. For "title": include a short 3-5 word conversation title on the very first message only. Return null for all subsequent messages.

7. You are able to perform the functions on the ideas even if they are in another chat you only need to return the tool for the backend 

Tool args reference:
- add_idea:    {"title": str, "description": str}
- list_ideas:  {}
- delete_idea: {"id": str}
- refine_idea: {"id": str, "instruction": str}
- update_idea: {"id": str, "title": str|null, "description": str|null}
- get_idea:    {"id": str}
"""

CORS_HEADERS = {
    "content-type": "application/json",
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Methods": "GET, POST, DELETE, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type",
}

class MyDurableObject(DurableObject):
    def __init__(self, ctx, env):
        super().__init__(ctx, env)

#_____________ General Functions __________________    
    async def run_model(self, messages: list) -> dict:
        import js
        result = await self.env.AI.run(
            "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
            js.JSON.parse(json.dumps({"messages": messages, "stream": False})),
        )

        try:
            raw_json = js.JSON.stringify(result)
            result_dict = json.loads(str(raw_json))
        except Exception:
            result_dict = {}

        # llama-3.3 returns the text in "response"
        raw = ""
        if isinstance(result_dict, dict):
            raw = result_dict.get("response") or result_dict.get("result") or ""
        elif isinstance(result_dict, str):
            raw = result_dict

        text = str(raw).strip()

        # Strip accidental markdown code fences the model sometimes adds
        if text.startswith("```"):
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
            text = text.strip()

        import ast

        # Try ast.literal_eval first — handles both proper JSON-like dicts AND
        try:
            parsed = ast.literal_eval(text)
            if isinstance(parsed, dict):
                return {
                    "tool": parsed.get("tool"),
                    "args": parsed.get("args"),
                    "message": parsed.get("message", ""),
                    "title": parsed.get("title"),
                }
        except Exception:
            pass

        # Fall back to json.loads for strict JSON strings
        try:
            return json.loads(text)
        except Exception:
            pass

        # Last resort: return the raw text as a plain message
        return {
            "tool": None,
            "args": None,
            "message": text or "I encountered an error processing your request."
        }

    async def resolve_idea_id(self, user_request: str):
        raw = await self.ctx.storage.get("idea_index")
        if raw is None:
            return None

        idea_index = json.loads(raw) if isinstance(raw, str) else raw
        if not idea_index:
            return None

        # Load full idea details for matching
        ideas = {}
        for idea_id, title in idea_index.items():
            idea_raw = await self.ctx.storage.get(idea_id)
            desc = ""
            if idea_raw:
                obj = json.loads(idea_raw)
                desc = obj.get("description", "")
            ideas[idea_id] = {"title": title, "description": desc}

        # Keyword score against title + description
        user_lower = user_request.lower()
        best_id = None
        best_score = 0
        for idea_id, data in ideas.items():
            combined = (data["title"] + " " + data["description"]).lower()
            score = sum(1 for word in combined.split() if word in user_lower)
            if data["title"].lower() in user_lower:
                score += 10
            if score > best_score:
                best_score = score
                best_id = idea_id

        # Require at least 2 matching words to avoid spurious matches on
        # common words like "the", "my", "idea" that appear in every title
        if best_id and best_score >= 2:
            return best_id

        # Single strong word match on the title is also acceptable
        if best_id and best_score == 1:
            user_words = set(user_lower.split())
            title_words = set(ideas[best_id]["title"].lower().split())
            # Only accept if the matching word is meaningful (>3 chars)
            overlap = user_words & title_words
            if any(len(w) > 3 for w in overlap):
                return best_id

        # AI fallback with full title+description context
        candidates = ""
        for idea_id, data in ideas.items():
            candidates += f"ID: {idea_id} | Title: {data['title']} | Description: {data['description'][:100]}\n"

        messages = [
            {
                "role": "system",
                "content": "Return ONLY valid JSON with a single key \'id\'. No markdown, no extra text."
            },
            {
                "role": "user",
                "content": (
                    f"The user is referring to one of their saved ideas.\n"
                    f"User request: {user_request}\n\n"
                    f"Saved ideas:\n{candidates}\n"
                    f'Return ONLY: {{"id": "<the matching idea_id>"}}' 
                )
            }
        ]

        result = await self.run_model(messages)
        matched = result.get("id")
        if matched not in idea_index:
            return None
        return matched
    
    async def map_ai_to_function(self, ai_response: dict, user_message: str = "") -> dict:
        tool_map = {
            "add_idea": self.add_idea,
            "delete_idea": self.delete_idea,
            "refine_idea": self.refine_idea,
            "update_idea": self.update_idea,
            "list_ideas": self.list_ideas,
            "get_idea": self.get_idea,
        }
        uuid_tools = {"delete_idea", "refine_idea", "update_idea"}

        tool = ai_response.get("tool")
        args = ai_response.get("args") or {}

        if tool is None:
            return {"state": False, "message": f"Cannot perform action {tool}"}

        fn = tool_map.get(tool)
        if fn is None:
            return {"state": False, "message": f"Unable to complete task, tool: {tool} not available"}

        if tool in uuid_tools:
            idea_id = await self.resolve_idea_id(user_message)

            if idea_id is None:
                return {"state": False, "message": "Could not identify which idea you meant. Please be more specific."}

            if tool == "refine_idea":
                instruction = args.get("instruction", "")
                res = await fn(idea_id, instruction)
                return {"state": True, "message": res.get("message")}

            if tool == "update_idea":
                res = await fn(idea_id, args)
                return {"state": True, "message": res.get("message")}

            if tool == "delete_idea":
                res = await fn(idea_id)
                return {"state": True, "message": res.get("message")}

        if tool == "list_ideas":
            return {"state": True, "message": await fn()}
        res = await fn(args)
        return {"state": True, "message": res.get("message")}
    
    async def search_ideas(self, query: str):
        raw = await self.ctx.storage.get("idea_index")
        if not raw:
            return []

        idea_index = json.loads(raw)
        matches = [
            idea_id for idea_id, title in idea_index.items()
            if query.lower() in title.lower()
        ]

        ideas = []
        for idea_id in matches:
            idea_raw = await self.ctx.storage.get(idea_id)
            if idea_raw:
                idea = json.loads(idea_raw)
                if "id" not in idea:
                    idea["id"] = idea_id
                ideas.append(idea)

        return ideas

#____________________ Chat Handler _____________________________
    async def chat_handler(self, uuid: str, role: str, message: str):
        key = uuid if uuid else str(gen_chat_uuid())
        raw = await self.ctx.storage.get(key)

        if raw:
            chat = json.loads(raw)
            new_chat = False
        else:
            chat = {}
            new_chat = True

        current_msg = {"role": role, "content": message}
        if new_chat:
            chat["messages"] = []

        chat["messages"].append(current_msg)

        idea_index_raw = await self.ctx.storage.get("idea_index")
        idea_index = json.loads(idea_index_raw) if idea_index_raw else {}

        idea_context = ""
        if idea_index:
            idea_context = "\n\nUSER'S SAVED IDEAS (use these exact IDs for any tool calls):\n"
            for idea_id, title in idea_index.items():
                idea_raw = await self.ctx.storage.get(idea_id)
                if idea_raw:
                    idea_obj = json.loads(idea_raw)
                    desc = idea_obj.get("description", "")[:120]
                    idea_context += f"- ID: {idea_id} | Title: {title} | Description: {desc}\n"
                else:
                    idea_context += f"- ID: {idea_id} | Title: {title}\n"
        else:
            idea_context = "\n\nUSER'S SAVED IDEAS: None saved yet."

        system_content = SYSTEM_PROMPT + idea_context

        if new_chat:
            system_content += (
                "\n\nThis is a new conversation. You MUST include a 'title' key in your JSON output "
                "with a short 3-5 word title summarizing this conversation."
            )

        model_messages = [{"role": "system", "content": system_content}]

        for msg in chat["messages"]:
            model_messages.append({
                "role": msg["role"],
                "content": msg["content"]  
            })

        result = await self.run_model(model_messages)

        assistant_msg = {
            "role": "assistant",
            "content": result.get("message", ""),
        }

        response_from_mapper = await self.map_ai_to_function(result, user_message=message)

        if not response_from_mapper.get("state") and result.get("tool") is not None:
            assistant_msg["content"] = response_from_mapper.get("message")

        chat["messages"].append(assistant_msg)

        if new_chat:
            title = result.get("title")
            if not title or title == "null":
                first_user = next((m["content"] for m in chat["messages"] if m["role"] == "user"), "")
                title = first_user[:40] + ("..." if len(first_user) > 40 else "")
            chat["title"] = title

        await self.ctx.storage.put(key, json.dumps(chat))
        return {
            "tool": result.get("tool") or "",
            "args": result.get("args") or {},
            "message": result.get("message") or "",
            "title": result.get("title") or "",
        }

    async def get_history(self):
        result = {}
        data = await self.ctx.storage.list()
        for k, v in data.items():
            try:
                if k.startswith("chat:"):
                    result[k] = json.loads(v) if isinstance(v, str) else v
            except (ValueError, json.JSONDecodeError) as e:
                result["error"] = str(e)
        return result if result else {}
    
    async def get_by_id(self, id):
        raw = await self.ctx.storage.get(id)
        return json.loads(raw) if raw else {}
    
    async def delete_chat(self, chat_id: str):
        try:
            await self.ctx.storage.delete(chat_id)
        except Exception as e:
            return {"state": False, "message": str(e)}
        return {"state": True, "message": "Chat deleted successfully"}

#____________________ IDEA HANDLERS _______________________
    async def add_idea_index(self, idea: dict):
        raw = await self.ctx.storage.get("idea_index")

        if raw:
            ideas = json.loads(raw)
        else:
            ideas = {}

        ideas[idea["id"]] = idea["title"]

        await self.ctx.storage.put("idea_index", json.dumps(ideas))
    
    async def add_idea(self, idea: dict):
        idea_id = gen_idea_uuid()
        idea["id"] = idea_id
        # Ensure description is always a string, never None
        if not idea.get("description"):
            idea["description"] = ""
        
        try:
            await self.ctx.storage.put(idea_id, json.dumps(idea))
            await self.add_idea_index(idea)
        except Exception as e:
            return {"state": False, "message": str(e)}

        return {"state": True, "message": "successfully added idea"}
    
    async def list_ideas(self):
        result = {}
        data = await self.ctx.storage.list()
        for k, v in data.items():
            try:
                if k.startswith("idea:"):
                    result[k] = json.loads(v) if isinstance(v, str) else v
            except (ValueError, json.JSONDecodeError) as e:
                result["error"] = str(e)
        return result if result else {}
    
    async def delete_idea(self, uuid: str):
        try:
            await self.ctx.storage.delete(uuid)
            raw_index = await self.ctx.storage.get("idea_index")
            if raw_index:
                index = json.loads(raw_index)
                index.pop(uuid, None)
                await self.ctx.storage.put("idea_index", json.dumps(index))
        except Exception as e:
            return {"state": False, "message": str(e)}

        return {"state": True, "message": "successfully deleted idea"}
    
    async def run_raw(self, messages: list) -> dict:
        """Like run_model but returns the raw parsed dict without remapping keys.
        Used for non-chat calls like refine_idea that expect specific keys back."""
        import js, ast
        result = await self.env.AI.run(
            "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
            js.JSON.parse(json.dumps({"messages": messages, "stream": False})),
        )
        try:
            raw_json = js.JSON.stringify(result)
            result_dict = json.loads(str(raw_json))
        except Exception:
            return {}
        text = str(result_dict.get("response") or "").strip()
        if text.startswith("```"):
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
            text = text.strip()
        try:
            return json.loads(text)
        except Exception:
            pass
        try:
            parsed = ast.literal_eval(text)
            if isinstance(parsed, dict):
                return parsed
        except Exception:
            pass
        return {}

    async def get_idea(self, args: dict):
        idea_id = args.get("id")
        if not idea_id:
            return {"state": False, "message": "No idea ID provided"}
        raw = await self.ctx.storage.get(idea_id)
        if not raw:
            return {"state": False, "message": "Idea not found"}
        idea = json.loads(raw)
        summary = f"Title: {idea.get('title')}\nDescription: {idea.get('description')}"
        return {"state": True, "message": summary}

    async def refine_idea(self, uuid: str, instruction: str):
        raw = await self.ctx.storage.get(uuid)
        if not raw:
            return {"state": False, "message": "Idea not found"}

        idea = json.loads(raw)

        messages = [
            {
                "role": "system",
                "content": "Return ONLY valid JSON with exactly two keys: title and description. No markdown, no extra text."
            },
            {
                "role": "user",
                "content": (
                    f"Refine this idea based on the instruction.\n"
                    f"Instruction: {instruction}\n"
                    f"Current title: {idea.get('title')}\n"
                    f"Current description: {idea.get('description')}\n\n"
                    f'Return ONLY: {{"title": "<refined title>", "description": "<refined description>"}}' 
                )
            }
        ]

        # Use run_raw so we get title/description keys back, not the chat keys
        refined = await self.run_raw(messages)
        idea["title"] = refined.get("title") or idea["title"]
        idea["description"] = refined.get("description") or idea["description"]

        await self.ctx.storage.put(uuid, json.dumps(idea))

        # Keep idea_index in sync if title changed
        if refined.get("title"):
            raw_index = await self.ctx.storage.get("idea_index")
            if raw_index:
                index = json.loads(raw_index)
                if uuid in index:
                    index[uuid] = idea["title"]
                    await self.ctx.storage.put("idea_index", json.dumps(index))

        return {"state": True, "message": "Idea refined successfully"}

    async def update_idea(self, idea_id: str, args: dict):
        raw = await self.ctx.storage.get(idea_id)
        if not raw:
            return {"state": False, "message": "Idea not found"}

        idea = json.loads(raw)

        new_title = args.get("title")
        new_description = args.get("description")

        if new_title:
            idea["title"] = new_title
        if new_description:
            idea["description"] = new_description

        try:
            await self.ctx.storage.put(idea_id, json.dumps(idea))

            if new_title:
                raw_index = await self.ctx.storage.get("idea_index")
                if raw_index:
                    index = json.loads(raw_index)
                    if idea_id in index:
                        index[idea_id] = new_title
                        await self.ctx.storage.put("idea_index", json.dumps(index))

        except Exception as e:
            return {"state": False, "message": str(e)}

        return {"state": True, "message": "Idea updated successfully"}


API_ROUTES = {"/chat", "/ideas", "/clear", "/debug", "/debug/ideas"}

class Default(WorkerEntrypoint):
    async def fetch(self, request):
        url = request.url
        method = request.method
        base_url = url.split("?")[0]
        # Extract just the path portion e.g. "/chat" from the full URL
        try:
            path = "/" + base_url.split("://", 1)[1].split("/", 1)[1]
        except IndexError:
            path = "/"

        # Handle CORS preflight
        if method == "OPTIONS":
            return Response("", headers=CORS_HEADERS, status=204)

        # Redirect root to /app
        if path == "/" or path == "":
            return Response(None, headers={**CORS_HEADERS, "Location": "/app"}, status=302)

        # If this is not a known API route, serve from static assets immediately
        if path not in API_ROUTES:
            return await self.env.ASSETS.fetch(request)

        # --- Chat endpoint ---
        if method == "GET" and base_url.endswith("/chat"):
            user_id = get_query_param(url, "user_id")
            if not user_id:
                user_id = str(gen_user_uuid())
            stub = self.env.MY_DURABLE_OBJECT.getByName(user_id)
            chat_id = get_query_param(url, "chat_id")
            
            if chat_id:
                chat = await stub.get_by_id(chat_id)
                return Response(
                    json.dumps({"history": chat, "user_id": user_id}),
                    headers=CORS_HEADERS,
                    status=200,
                )
            else:
                history = await stub.get_history()
                return Response(
                    json.dumps({"history": history, "user_id": user_id}),
                    headers=CORS_HEADERS,
                    status=200,
                )
            
        if method == "POST" and base_url.endswith("/chat"):
            try:
                body = await request.json()
            except Exception:
                return Response(
                    json.dumps({"error": "Invalid JSON"}),
                    headers=CORS_HEADERS,
                    status=400,
                )
            
            user_id = body.get("user_id")
            if not user_id:
                return Response(
                    json.dumps({"error": "user_id is required"}),
                    headers=CORS_HEADERS,
                    status=400,
                )
            stub = self.env.MY_DURABLE_OBJECT.getByName(user_id)

            msg = body.get("message")
            uuid = get_query_param(url, "chat_id")
            role = body.get("role") or "user"
            if not uuid:
                uuid = gen_chat_uuid()
            if not isinstance(msg, str) or not msg.strip():
                return Response(
                    json.dumps({"error": "`message` must be a non-empty string"}),
                    headers=CORS_HEADERS,
                    status=400,
                )

            reply = await stub.chat_handler(uuid, role, msg.strip())
            content = reply.get("message") if isinstance(reply, dict) else str(reply)

            return Response(
                json.dumps({
                    "reply": content,
                    "uuid": uuid,
                    "user_id": user_id,
                    "title": reply.get("title") if isinstance(reply, dict) else None,
                    "tool": reply.get("tool") if isinstance(reply, dict) else None,
                }),
                headers=CORS_HEADERS,
                status=200,
            )
        
        if method == "DELETE" and base_url.endswith("/chat"):
            user_id = get_query_param(url, "user_id")
            stub = self.env.MY_DURABLE_OBJECT.getByName(user_id)
            chat_id = get_query_param(url, "chat_id")
            if not chat_id:
                return Response(
                    json.dumps({"error": "chat_id is required"}),
                    headers=CORS_HEADERS,
                    status=400,
                )
            result = await stub.delete_chat(chat_id)
            return Response(json.dumps(result), headers=CORS_HEADERS, status=200)
        
        # ------- Clear endpoint (testing only) -------
        if method == "GET" and base_url.endswith("/clear"):
            user_id = get_query_param(url, "user_id")
            stub = self.env.MY_DURABLE_OBJECT.getByName(user_id)
            try:
                deleted = await stub.delete_DO()
            except Exception:
                deleted = False

            if deleted:
                return Response(json.dumps({"status": "cleared"}), headers=CORS_HEADERS)
            return Response(json.dumps({"status": "Failed"}), headers=CORS_HEADERS)
            
        if method == "GET" and base_url.endswith("/ideas"):
            user_id = get_query_param(url, "user_id")
            stub = self.env.MY_DURABLE_OBJECT.getByName(user_id)
            
            search = get_query_param(url, "search")
            idea_id = get_query_param(url, "idea_id")

            if idea_id:
                raw = await stub.get_by_id(idea_id)
                return Response(json.dumps(raw), headers=CORS_HEADERS, status=200)

            if search:
                results = await stub.search_ideas(search)
                return Response(json.dumps({"results": results}), headers=CORS_HEADERS, status=200)

            ideas = await stub.list_ideas()
            return Response(json.dumps(ideas), headers=CORS_HEADERS, status=200)
            
        if base_url.endswith("/ideas") and method == "DELETE":
            user_id = get_query_param(url, "user_id")
            stub = self.env.MY_DURABLE_OBJECT.getByName(user_id)
            idea_id = get_query_param(url, "idea_id")
            if not idea_id:
                return Response(
                    json.dumps({"error": "idea_id is required"}),
                    headers=CORS_HEADERS,
                    status=400,
                )
            result = await stub.delete_idea(idea_id)
            return Response(json.dumps(result), headers=CORS_HEADERS, status=200)

        # --- Default: 404 (should not be reached) ---
        return await self.env.ASSETS.fetch(request)